#!/bin/bash

gcc -O3 -std=gnu99 -Wall -Wextra -Werror -pedantic -o count_down count_down.c
gcc -O3 -std=gnu99 -Wall -Wextra -Werror -pedantic -o count_up count_up.c 
gcc -O3 -std=gnu99 -Wall -Wextra -Werror -pedantic -o insn insn.c

echo -n "count up: " ; perf stat -r 100 ./count_up 2>&1 | grep "time elapsed"
echo -n "count dn: " ; perf stat -r 100 ./count_down 2>&1 | grep "time elapsed"
echo -n "insn  up: " ; perf stat -r 20 ./insn u 2>&1 | grep "time elapsed"
echo -n "insn  dn: " ; perf stat -r 20 ./insn d 2>&1 | grep "time elapsed"
echo -n "insn  lt: " ; perf stat -r 20 ./insn l 2>&1 | grep "time elapsed"

objdump -S count_up | grep -A 999 "<main>" | sed -e '/^$/,$d'
objdump -S count_down | grep -A 999 "<main>" | sed -e '/^$/,$d'
objdump -S insn | grep -A 999 "<insn_up_eq>:" | sed -e '/^$/,$d'
objdump -S insn | grep -A 999 "<insn_down>:" | sed -e '/^$/,$d'
objdump -S insn | grep -A 999 "<insn_up_lt>:" | sed -e '/^$/,$d'
